// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sypcypkpeoiiazkprdhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5cGN5cGtwZW9paWF6a3ByZGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNDA3NDEsImV4cCI6MjA1NDYxNjc0MX0.vaJQJ6YXmtxJv81KK7tPtzKWK9iBXAsGXtLLlgP2Xeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);